CREATE TABLE IF NOT EXISTS expedia_raw
                       (
                            id INT PRIMARY KEY,
                            date_time TIMESTAMP,
                            site_name INT,
                            posa_continent INT,
                            user_location_country INT,
                            user_location_region INT,
                            user_location_city INT,
                            orig_destination_distance DOUBLE PRECISION,
                            user_id INT,
                            is_mobile SMALLINT,
                            is_package SMALLINT,
                            channel INT,
                            srch_ci DATE,
                            srch_co DATE,
                            srch_adults_cnt SMALLINT,
                            srch_children_cnt SMALLINT,
                            srch_rm_cnt SMALLINT,
                            srch_destination_id INT,
                            srch_destination_type_id SMALLINT,
                            is_booking SMALLINT,
                            cnt INT,
                            hotel_continent SMALLINT,
                            hotel_country INT,
                            hotel_market INT,
                            hotel_cluster SMALLINT
                       );